### ISSUE TITLE
PS 1.7.6.7 - Not working

### ISSUE THREAD

**Issue by HartLarsson** [MathiasReker/loginascustomer#2]
By clicking the button in the customer page in BO will be redirected to login form asking to login.
In this way is not working.

PS 1.7.6.7
theme Warehouse 4.3.4
PHP 7.2

**Comment by MathiasReker** [comment]
Hello

It is fixed in the latest version: https://github.com/MathiasReker/loginascustomer/releases/tag/2.0.0

**Comment by myfender** [comment]
I have the same problem.
By clicking the button in the customer page in BO will be redirected to login form asking to login.
In this way is not working.

PS 1.7.6.8
theme Warehouse 4.3.6
PHP 7.2

**Comment by MathiasReker** [comment]
Hello

I made the module compatible with the newest PrestaShop 1.7 as well.

Please update to this version: https://github.com/MathiasReker/loginascustomer/releases/tag/2.0.0
