### ISSUE TITLE
PS 1.7.6.8 not working

### ISSUE THREAD

**Issue by myfender** [MathiasReker/loginascustomer#3]
I have the same problem.
By clicking the button in the customer page in BO will be redirected to login form asking to login.
In this way is not working.

PS 1.7.6.8
theme Warehouse 4.3.6
PHP 7.2

PS: Version 2.0.0 always sees it as 1.0.1

**Comment by myfender** [comment]
I have opened a new PR to resolve this issue

**Comment by MathiasReker** [comment]
Fixed here: https://github.com/MathiasReker/loginascustomer/pull/4

**Comment by MathiasReker** [comment]
Thanks @myfender !

**Comment by myfender** [comment]
> Thanks @myfender !

You're welcome!
