### ISSUE TITLE
Not work in 1.7.7

### ISSUE THREAD

**Issue by tecnopaks** [MathiasReker/loginascustomer#6]
Hello, I have my store on 1.7.7.4

The module appears the button but when clicking it redirects to the login page. without logging in as a customer.
?back=my-account

**Comment by wiro24** [comment]
Same problem in Prestashop 1.7.7.1

**Comment by gadnis** [comment]
It works when customer has account and it is not when customer is a guest. 

I try my self to figure it out how to allow guest login, but if some one has a suggestion, please no hesitate 😁  Maybe module author could help on this one? @MathiasReker  ?

**Comment by hennaboy** [comment]
Unfortunately it does not work on 1.7.7.8 clicking login as customer takes you to a new page but with request for login details.

**Comment by gadnis** [comment]
@hennaboy has that customer registered account or is he a guest?

**Comment by hennaboy** [comment]
Registered accounts tried several.

**Comment by MathiasReker** [comment]
new version released.
